# Generated by Django 2.1 on 2018-12-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_name', models.CharField(default='', max_length=50, verbose_name='英文名称')),
                ('cn_name', models.CharField(default='', max_length=50, verbose_name='中文名称')),
                ('code', models.CharField(default='', max_length=50, verbose_name='16进制编号')),
                ('unit', models.CharField(default='', max_length=50, verbose_name='单位')),
                ('description', models.CharField(default='', max_length=100, verbose_name='描述信息')),
            ],
        ),
    ]
