# Generated by Django 2.1 on 2018-12-16 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_functioncode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('data', models.CharField(max_length=50, verbose_name='传感器返回数据')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='portal.Sensor', verbose_name='传感器')),
            ],
        ),
    ]
