# Generated by Django 2.1 on 2018-12-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='display_data',
            field=models.CharField(default='', max_length=50, verbose_name='界面显示数据'),
        ),
        migrations.AlterField(
            model_name='message',
            name='data',
            field=models.CharField(default='', max_length=50, verbose_name='传感器返回数据'),
        ),
    ]
